### ISSUE TITLE
this is a logger lmao

### ISSUE THREAD

**Issue by Wang-sus** [W4TERR/discord-console-hack#1]
i took one glance at the code, you should have obfuscated it dumbass

**Comment by FlyingndCoding** [comment]
Ye exactly dont use it

**Comment by FlyingndCoding** [comment]
anyway this does not work anymore  it will return you syntax error

**Comment by W4TERR** [comment]
@FlyingndCoding it only returns an error because I deleted the webhook used in it :)

**Comment by W4TERR** [comment]
@Wang-sus If it makes you feel MUCH better, the reason why it wasn't obfuscated is because I honestly was too lazy to do so. It has gotten so much people without the obfuscation that I didn't bother fixing it. If you want to help me on other projects, add me on discord 😄 (thotty#1337)

**Comment by gimmy74** [comment]
its not that hard to obfuscate code but you shouldn't be making discord scripts for malicious reasons.
